HT_23/auth_app/urls.py
from django.urls import path

from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
]

HT_23/goods_parsing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('auth_app.urls')),
    path('', include('products_app.urls')),
    path('cart/', include('cart_app.urls')),
]

HT_23/products_app/urls.py
from django.urls import path

from products_app import views

app_name = 'products_app'

urlpatterns = [
    path('products/', views.ProductsListView.as_view(), name='products'),
    path('products/cat/<category>',
         views.ProductsListByCategoryView.as_view(), name='products_by_category'),
    path('product/<pk>', views.ProductDetailView.as_view(), name='product_details'),
    path('product/edit/<pk>', views.ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<pk>', views.ProductDeleteView.as_view(),
         name='delete_product'),
    path('parse/', views.ParseFormView.as_view(), name='parse'),

    # API patterns
    path('api/products/', views.ProductsAPIView.as_view(), name='api_products'),
    path('api/products/<pk>/', views.ProductAPIView.as_view(), name='api_product'),
    path('api/parse/', views.ProductsParseAPIView.as_view(), name='api_parse'),
]

HT_23/products_app/models.py
from django.db import models


class Product(models.Model):
    id = models.CharField(max_length=20, primary_key=True)
    name = models.CharField(max_length=200)
    brand_name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    link = models.CharField(max_length=100)
    category = models.CharField(max_length=100)

    def __str__(self):
        return self.name

HT_23/products_app/forms.py
from django import forms


class EnterIdsForm(forms.Form):
    id_list = forms.CharField(label="Enter products IDs, separated by coma")

HT_23/products_app/views/api_views.py
import subprocess
from sys import stdout, stdin, stderr
from pathlib import Path

from rest_framework.generics import RetrieveUpdateDestroyAPIView, ListCreateAPIView
from rest_framework.views import APIView
from rest_framework.permissions import IsAdminUser
from rest_framework.response import Response

from products_app.serializers import ProductsSerializer
from products_app.models import Product


class ProductsAPIView(ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductsSerializer

    def get_permissions(self):
        if self.request.method == 'GET':
            return []
        else:
            return [IsAdminUser()]


class ProductAPIView(RetrieveUpdateDestroyAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductsSerializer

    def get_permissions(self):
        if self.request.method == "GET":
            return []
        else:
            return [IsAdminUser()]


class ProductsParseAPIView(APIView):
    def get_permissions(self):
        return [IsAdminUser()]

    def post(self, request):
        self.start_subprocess(request.data)
        return Response(request.data.get('id_list'))

    def start_subprocess(self, id_list):
        project_root = Path(__file__).parent.parent.parent
        manage_py_path = Path(project_root, "manage.py")
        command = f'python {manage_py_path} shell --command="from products_app.parser import Parser; Parser({id_list}).run()"'
        subprocess.Popen(command, shell=True, stdin=stdin,
                         stdout=stdout, stderr=stderr)

HT_23/products_app/views/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView, FormView, UpdateView, DeleteView
from django.contrib.auth.mixins import UserPassesTestMixin
from products_app.tasks import start_subprocess


from products_app.models import Product
from products_app.forms import EnterIdsForm


class ProductsListView(ListView):
    model = Product
    template_name = "products.html"
    context_object_name = "products"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        categories = set(Product.objects.values_list('category', flat=True))
        context['categories'] = categories

        return context


class ProductsListByCategoryView(ListView):
    model = Product
    template_name = "products.html"
    context_object_name = "products"

    def get_queryset(self):
        category = self.kwargs.get('category')
        return Product.objects.filter(category=category)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        category = self.kwargs.get('category')
        context['categories'] = [category]

        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = "product_details.html"
    context_object_name = "product"


class ParseFormView(UserPassesTestMixin, FormView):
    template_name = 'parse.html'
    form_class = EnterIdsForm

    def test_func(self):
        return self.request.user.is_superuser

    def post(self, request, *args, **kwargs):
        form = EnterIdsForm(request.POST)
        context = {'form': EnterIdsForm()}

        if form.is_valid():
            id_list = form.cleaned_data['id_list'].split(',')
            id_list = set(item.strip() for item in id_list)
            self.start_subprocess(id_list)
            start_subprocess.delay(list(id_list))

            context.update({'message': 'Products scraping start successfully'})
        else:
            context.update({'message': 'Form data unsuccessfully'})

        return render(request, 'parse.html', context=context)

    def start_subprocess(self, id_list):
        start_subprocess(id_list)


def is_superuser(user):
    return user.is_superuser


class ProductUpdateView(UserPassesTestMixin, UpdateView):
    model = Product
    template_name = 'edit_product.html'
    fields = ['id', 'name', 'brand_name', 'price',
              'description', 'link', 'category']
    success_url = reverse_lazy('products_app:products')

    def test_func(self):
        return self.request.user.is_superuser


class ProductDeleteView(UserPassesTestMixin, DeleteView):
    model = Product
    template_name = 'delete_product.html'
    success_url = reverse_lazy('products_app:products')

    def test_func(self):
        return self.request.user.is_superuser

HT_23/products_app/templates/delete_product.html
{% extends 'base.html' %}

{% block title_block %}GParser : delete product{% endblock %}

{% block main_block %}
<h2 class="page-header">Delete Product</h2>
<form method="post">
    {% csrf_token %}
    <div class="form-container">
        <p class="warning-text">Are you sure you want to delete product completely?</p>

        <button type="submit" class="interface-button">CONFIRM</button>
    </div>
</form>
<a href="{% url 'products_app:products' %}" class="interface-button">CANCEL</a>
{% endblock %}

HT_23/products_app/templates/edit_product.html
{% extends 'base.html' %}

{% block title_block %}GParser : edit product{% endblock %}

{% block main_block %}
<h2 class="page-header">Edit Product</h2>
<form method="post">
    <div class="form-container">
        {% csrf_token %}
        {{ form.as_p }}
    </div>

    <button type="submit" class="interface-button">Save</button>
</form>
{% endblock %}

HT_23/products_app/templates/parse.html
{% extends 'base.html' %}

{% block title_block %}GParser : parse{% endblock %}

{% block main_block %}

<h2 class="page-header">Parse products</h2>

<form action="{% url 'products_app:parse' %}" method="post">
    {% csrf_token %}
    {{ form }}
    <p class="response-result-message">{{ message }}</p>
    <button type="submit" class="btn btn-primary my-3">Parse</button>
</form>

{% endblock %}

HT_23/products_app/templates/product_details.html
{% extends 'base.html' %}

{% block title_block %} GParser : product details {% endblock %}

{% block main_block %}
<div class="container product-properties">
    <div class="header-container">
        <h2 class="page-header">Product properties</h2>
        {% if user.is_superuser %}
        <div class="buttons-container">
            <a href="{% url 'products_app:product_edit' product.id %}" class="interface-button">EDIT</a>
            <a href="{% url 'products_app:delete_product' product.id %}" class="interface-button">REMOVE</a>
        </div>
        {% endif %}
    </div>

    <div class="product-property">
        <span>Product ID:</span>
        <span>{{ product.id }}</span>
    </div>
    <div class="product-property">
        <span>Product name:</span>
        <span>{{ product.name }}</span>
    </div>
    <div class="product-property">
        <span>Product brand:</span>
        <span>{{ product.brand_name }}</span>
    </div>
    <div class="product-property">
        <span>Product description:</span>
        <span>{{ product.description }}</span>
    </div>
    <div class="product-property">
        <span>Regular price:</span>
        <span>{{ product.price }}</span>
    </div>
    <div class="product-property">
        <span>Product link:</span>
        <span>{{ product.link }}</span>
    </div>
</div>
{% endblock %}

HT_23/products_app/templates/products.html
{% extends 'base.html' %}
{% load static %}

{% block links_block %}
<script src="{% static 'products_app/js/scripts.js' %}"></script>
{% endblock %}

{% block title_block %}GParser : products{% endblock %}

{% block main_block %}
<h2 class="page-header">Products page</h2>

<ul class="categories-container">
    <li class="categories-header-item">
        <h3 class="categories-header">CATEGORIES:</h3>
    </li>
    {% for category in categories %}
    <li>
        <a class="interface-button" href="{% url 'products_app:products_by_category' category%}">{{ category }}</a>
    </li>
    {% endfor %}

</ul>

<table>
    <thead>
        <tr>
            <th class="table-header">Product Name</th>
            <th class="table-header">Product ID</th>
            <th class="table-header">Product price</th>
            {% if user.is_authenticated %}
            <th class="table-header">Add to cart</th>
            {% endif %}
        </tr>
    </thead>
    <tbody id="products_table">
        {% for product in products %}
        <tr>
            <td><a href="{% url 'products_app:product_details' product.id %}">{{ product.name }}</a></td>
            <td>{{ product.id }}</td>
            <td>{{ product.price }}</td>
            {% if user.is_authenticated %}
            <td><a href="#" class="add-link" data-product_id="{{ product.id }}" data-type="add-to-cart-btn">Add</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}