HT_23/auth_app/urls.py
from django.urls import path

from auth_app import views

app_name = 'auth_app'

urlpatterns = [
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout')
]

HT_23/cart_app/urls.py
from django.urls import path

from cart_app import views

app_name = 'cart_app'

urlpatterns = [
    path('', views.cart, name='cart'),
    path('add/<product_id>', views.add_product, name='add_product'),
    path('remove/<product_id>', views.remove_product, name='remove_product'),
    path('inc/<product_id>', views.inc_product, name='inc_product'),
    path('dec/<product_id>', views.dec_product, name='dec_product'),
    path('clear/', views.clear, name='clear'),

    # API urls
    path('api/', views.CartAPIView.as_view(), name='cart_API'),
    path('api/<pk>', views.CartAPIView.as_view(), name='cart_API'),
]

HT_23/goods_parsing/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    path('accounts/', include('auth_app.urls')),
    path('', include('products_app.urls')),
    path('cart/', include('cart_app.urls')),
]

HT_23/products_app/urls.py
from django.urls import path

from products_app import views

app_name = 'products_app'

urlpatterns = [
    path('products/', views.ProductsListView.as_view(), name='products'),
    path('products/cat/<category>',
         views.ProductsListByCategoryView.as_view(), name='products_by_category'),
    path('product/<pk>', views.ProductDetailView.as_view(), name='product_details'),
    path('product/edit/<pk>', views.ProductUpdateView.as_view(), name='product_edit'),
    path('product/delete/<pk>', views.ProductDeleteView.as_view(),
         name='delete_product'),
    path('parse/', views.ParseFormView.as_view(), name='parse'),

    # API patterns
    path('api/products/', views.ProductsAPIView.as_view(), name='api_products'),
    path('api/products/<pk>/', views.ProductAPIView.as_view(), name='api_product'),
    path('api/parse/', views.ProductsParseAPIView.as_view(), name='api_parse'),
]

HT_23/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head_block %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    {% block links_block %}
    {% endblock %}
    <title>
        {% block title_block %} GParser {% endblock %}
    </title>
    {% endblock %}
</head>

<body>
    <header class="section">
        <div class="section-container">
            <nav class="nav-menu">
                {% block nav_block %}
                <ul class="nav-links">
                    {% if user.is_superuser %}
                    <li><a href="{% url 'products_app:parse' %}" class="nav-link">PARSE</a></li>
                    {% endif %}
                    <li><a href="{% url 'products_app:products' %}" class="nav-link">PRODUCTS</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'cart_app:cart' %}" class="nav-link">CART</a></li>
                    {% endif %}
                </ul>
                <div class="nav-login">
                    {% if user.is_authenticated %}
                    <span class="nav-username">👤 {{user.username}}</span>
                    <a href="{% url 'auth_app:logout' %}" class="nav-link">LOGOUT</a>
                    {% else %}
                    <a href="{% url 'auth_app:login' %}" class="nav-link">LOGIN</a>
                    {% endif %}
                    {% endblock %}
                </div>

            </nav>
        </div>
    </header>

    <main class="section">
        <div class="section-container">
            {% block main_block %}
            {% endblock %}
        </div>
    </main>
</body>

</html>