HT_19/goods_parsing/parse/urls.py
from django.urls import path

from . import views

app_name = "parse"

urlpatterns = [
    path("parse/", views.EnterIdsFormView.as_view(), name="parse"),
    path("products/", views.ProductsListView.as_view(), name="products"),
    path("product/<pk>", views.ProductDetailView.as_view(), name="product_details"),    
]

HT_19/goods_parsing/parse/models.py
from django.db import models


class Product(models.Model):
    id = models.CharField(max_length=10, primary_key=True)
    name = models.CharField(max_length=100)
    brand_name = models.CharField(max_length=100)
    regular_price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    link = models.CharField(max_length=100)

    def __str__(self):
        return self.name

HT_19/goods_parsing/parse/views.py
import subprocess
from sys import stdout, stdin, stderr
from pathlib import Path

from django.shortcuts import render
from django.views.generic import ListView
from django.views.generic import DetailView
from django.views.generic import FormView

from .models import Product
from .forms import EnterIdsForm


class EnterIdsFormView(FormView):
    template_name = 'parse/index.html'
    form_class = EnterIdsForm

    def post(self, request, *args, **kwargs):
        form = EnterIdsForm(request.POST)
        context = {'form': EnterIdsForm()}

        if form.is_valid():
            id_list = form.cleaned_data['id_list'].split(',')
            id_list = set(item.strip() for item in id_list)
            self.start_subprocess(id_list)

            context.update({'message': 'Products scraping start successfully'})
        else:
            context.update({'message': 'Form data unsuccessfully'})

        return render(request, 'parse/index.html', context=context)

    def start_subprocess(self, id_list):
        project_root = Path(__file__).parent.parent
        manage_py_path = Path(project_root, "manage.py")
        command = f'python {manage_py_path} shell --command="from parse.parser import Parser; Parser({id_list}).run()"'
        subprocess.Popen(command, shell=True, stdin=stdin, stdout=stdout, stderr=stderr)


class ProductsListView(ListView):
    model = Product
    template_name = "parse/my_products.html"
    context_object_name = "products"


class ProductDetailView(DetailView):
    model = Product
    template_name = "parse/product.html"
    context_object_name = "product"

HT_19/goods_parsing/parse/templates/parse/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'parse/css/style.css' %}">
    <title>Goods Parser</title>
</head>

<body>
    <header>
        <nav class="nav-panel">
            <ul class="nav-links">
                <li class="nav-link"><a href="{% url 'parse:parse' %}">Add Products</a></li>
                <li class="nav-link"><a href="{% url 'parse:products' %}">My Products</a></li>
                <li class="nav-link"><a href="{% url 'cart:cart' %}">Cart</a></li>
            </ul>
        </nav>
        <h1 class="main-header">Products Parser</h1>
    </header>
    <main>
        {% block main %}{% endblock %}
    </main>
</body>

</html>

HT_19/goods_parsing/parse/templates/parse/index.html
{% extends "parse/base.html" %}
{% block main %}
<div class="container">
    <h2 class="page-header">
        Start parcing form
    </h2>

    <form action="{% url 'parse:parse' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <p class="response-result-message">{{ message }}</p>
        <button type="submit" class="btn btn-primary my-3">Parse</button>

        {{ user.is_authenticated }}
    </form>


</div>
{% endblock %}

HT_19/goods_parsing/parse/templates/parse/my_products.html
{% extends "parse/base.html" %}
{% block main %}
<div class="container">
    <h2 class="page-header">
        Parsed Products List
    </h2>

    <table>
        <thead>
            <tr>
                <th class="table-header">Product Name</th>
                <th class="table-header">Product ID</th>
                <th class="table-header">Product price</th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
            <tr>
                <td><a href="{% url 'parse:product_details' product.id %}">{{ product.name }}</a></td>
                <td>{{ product.id }}</td>
                <td>{{ product.regular_price }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

HT_19/goods_parsing/parse/templates/parse/product.html
{% extends "parse/base.html" %}
{% block main %}
<div class="container">
    <h2 class="page-header">Product properties</h2>
    <div class="product-property">
        <span>Product ID:</span>
        <span>{{ product.id }}</span>
    </div>
    <div class="product-property">
        <span>Product name:</span>
        <span>{{ product.name }}</span>
    </div>
    <div class="product-property">
        <span>Product brand:</span>
        <span>{{ product.brand_name }}</span>
    </div>
    <div class="product-property">
        <span>Regular price:</span>
        <span>{{ product.regular_price }}</span>
    </div>
    <div class="product-property">
        <span>Product link:</span>
        <span>{{ product.link }}</span>
    </div>
</div>
{% endblock %}